# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_barrage_options.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_barrage_options(object):
    def setupUi(self, Dialog_barrage_options):
        Dialog_barrage_options.setObjectName("Dialog_barrage_options")
        Dialog_barrage_options.resize(250, 204)
        self.groupBox_barrageSettings = QtWidgets.QGroupBox(Dialog_barrage_options)
        self.groupBox_barrageSettings.setGeometry(QtCore.QRect(10, 10, 231, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_barrageSettings.setFont(font)
        self.groupBox_barrageSettings.setObjectName("groupBox_barrageSettings")
        self.label_textSize = QtWidgets.QLabel(self.groupBox_barrageSettings)
        self.label_textSize.setGeometry(QtCore.QRect(10, 30, 31, 21))
        self.label_textSize.setObjectName("label_textSize")
        self.comboBox_textSize = QtWidgets.QComboBox(self.groupBox_barrageSettings)
        self.comboBox_textSize.setGeometry(QtCore.QRect(40, 31, 67, 21))
        self.comboBox_textSize.setObjectName("comboBox_textSize")
        self.label_textSpeed = QtWidgets.QLabel(self.groupBox_barrageSettings)
        self.label_textSpeed.setGeometry(QtCore.QRect(120, 30, 31, 21))
        self.label_textSpeed.setObjectName("label_textSpeed")
        self.comboBox_textSpeed = QtWidgets.QComboBox(self.groupBox_barrageSettings)
        self.comboBox_textSpeed.setGeometry(QtCore.QRect(150, 30, 67, 21))
        self.comboBox_textSpeed.setObjectName("comboBox_textSpeed")
        self.groupBox_PlayRes = QtWidgets.QGroupBox(Dialog_barrage_options)
        self.groupBox_PlayRes.setGeometry(QtCore.QRect(10, 90, 231, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_PlayRes.setFont(font)
        self.groupBox_PlayRes.setObjectName("groupBox_PlayRes")
        self.label_X = QtWidgets.QLabel(self.groupBox_PlayRes)
        self.label_X.setGeometry(QtCore.QRect(110, 30, 16, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_X.setFont(font)
        self.label_X.setObjectName("label_X")
        self.lineEdit_PlayResX = QtWidgets.QLineEdit(self.groupBox_PlayRes)
        self.lineEdit_PlayResX.setGeometry(QtCore.QRect(20, 30, 81, 21))
        self.lineEdit_PlayResX.setObjectName("lineEdit_PlayResX")
        self.lineEdit_PlayResY = QtWidgets.QLineEdit(self.groupBox_PlayRes)
        self.lineEdit_PlayResY.setGeometry(QtCore.QRect(130, 30, 81, 21))
        self.lineEdit_PlayResY.setObjectName("lineEdit_PlayResY")
        self.pushButton_confirm = QtWidgets.QPushButton(Dialog_barrage_options)
        self.pushButton_confirm.setGeometry(QtCore.QRect(110, 170, 61, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_confirm.setFont(font)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_barrage_options)
        self.pushButton_cancel.setGeometry(QtCore.QRect(180, 170, 61, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")

        self.retranslateUi(Dialog_barrage_options)
        QtCore.QMetaObject.connectSlotsByName(Dialog_barrage_options)

    def retranslateUi(self, Dialog_barrage_options):
        _translate = QtCore.QCoreApplication.translate
        Dialog_barrage_options.setWindowTitle(_translate("Dialog_barrage_options", "弹幕首选项"))
        self.groupBox_barrageSettings.setTitle(_translate("Dialog_barrage_options", "默认弹幕设置"))
        self.label_textSize.setText(_translate("Dialog_barrage_options", "字号"))
        self.label_textSpeed.setText(_translate("Dialog_barrage_options", "速度"))
        self.groupBox_PlayRes.setTitle(_translate("Dialog_barrage_options", "默认视频分辨率"))
        self.label_X.setText(_translate("Dialog_barrage_options", "×"))
        self.pushButton_confirm.setText(_translate("Dialog_barrage_options", "确定"))
        self.pushButton_cancel.setText(_translate("Dialog_barrage_options", "取消"))
